### ISSUE TITLE
install fail on linux (pypiwin32)

### ISSUE THREAD

**Issue by drammock** [LABSN/tdtpy#28]
```
Collecting tdtpy
  Downloading TDTPy-0.10.1-py3-none-any.whl (358 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 358.8/358.8 kB 81.6 MB/s eta 0:00:00
Collecting pypiwin32
  Downloading pypiwin32-223-py3-none-any.whl (1.7 kB)
Requirement already satisfied: numpy in /opt/miniforge3/envs/badbaby/lib/python3.11/site-packages (from tdtpy) (1.24.2)
Requirement already satisfied: pycparser in /opt/miniforge3/envs/badbaby/lib/python3.11/site-packages (from CFFI>=1->rtmixer) (2.21)
  Downloading pypiwin32-219.zip (4.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 19.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-pm73qp4c/pypiwin32_b224397bd53040c1a9ef7440dd7d097c/setup.py", line 121
          print "Building pywin32", pywin32_version
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

**Comment by larsoner** [comment]
Do you have this on `main` as well? I think we fixed this recently so it at least installs. It'll be completely unusable but it should install...

**Comment by drammock** [comment]
nevermind. I forgot that this package isn't supposed to work w/ Linux.
